spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course_erp_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true



security:
  jwt:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAotZzVPC9kxZmwYuKmFjNyoDE5WSFJ+g4COTIRTcV03QplWm6jCfI+a6t4UltbUafM/fcO2BiUY5i4l2Lp9DKZCe8C/cbZ5HbyxN7tZVOivSoCzPdpPoUmYPPAgwhPlkoviIuQkpxTuwF2Je41gGfeTJJVe50fvAO098aobFzjL5A9UkioTO6iDFaYWh2XlelpPwAY5XXeIIk8HeKtRBUIoFeqQLjH19txeLERzPtnuepO3gr5zKHHmcTo7YWczbvnWyJIyE4KrFNejp+rAEn+v0RvolZUhUWNHE7Y18fQ56HgQhaUsWJu4mIO8A2Kn8jdBnoaZ9bfhosZdtccoRbuwIDAQAB
    private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCi1nNU8L2TFmbBi4qYWM3KgMTlZIUn6DgI5MhFNxXTdCmVabqMJ8j5rq3hSW1tRp8z99w7YGJRjmLiXYun0MpkJ7wL9xtnkdvLE3u1lU6K9KgLM92k+hSZg88CDCE+WSi+Ii5CSnFO7AXYl7jWAZ95MklV7nR+8A7T3xqhsXOMvkD1SSKhM7qIMVphaHZeV6Wk/ABjldd4giTwd4q1EFQigV6pAuMfX23F4sRHM+2e56k7eCvnMoceZxOjthZzNu+dbIkjITgqsU16On6sASf6/RG+iVlSFRY0cTtjXx9DnoeBCFpSxYm7iYg7wDYqfyN0Gehpn1t+Gixl21xyhFu7AgMBAAECggEABbgfWFZt9THqkmSFyOpqyhf3CJE6cgjMwS/T5QtfSiTeNS660QXrn/Gvjr7TR89hwlACf+wmSRtApo0VjrwnPwTojyvLe+F83c7PabTbqSmFCPk7GvCyaV6tR24XZ25ji5m4bOgCNXzpskRcFe1elqQaZCLVQ3plhp4KrXQFvkgvE4RcK/5EaAYT/qhTjQMfjiyIcHKJp/o6XHparAz4qTCATQklecAgOC1Ta94ddvKlRs2ZFfhcQk6Qg42XFuHNOPXvVVLq+Fau8ogWmiXu+4Lv1XjAKi8OtQhhWg4CD2xMiTuYweJPbWDc5+j5CqebxHLQFBJcMxb6Q/CAbSWc2QKBgQDaBZlTfAeOAgefYXmkVR0OwcgOsFLRpYwdjjlS8RNteRnC4fnVTgzG9f8qZPvsCgXsZGJZDhTr/6ktbJ5HS7hxm7FhwE3AH94vaDJS8yXEWVKhsxSTskdm9M0myPFdN0bIp67eFK93Ibd5EPNUNM4kEQWxplR+PZNRBDONyF6BYwKBgQC/M/w9whomnUSWWVQT0UNa7g7hE1NrhY7y3NttfEInHqbxfvfnZ1fdczbzl8N3F6XW6L1rI6iKryRz4kqV1E2ZylYJrNfKcU+mDDgQk3MtXjenQLPZ3DQpZcUjOQBNsFFeL2Uyy2AjckSL/rUuhLZnkc+kM0lCi9tHNhNoUNG3yQKBgHs7HO4ONerzhMF2hB35qeH0cBK1YSp0ix0NjaMu9k8zWvdHaUJCyoAO/XpF+Arzo2N5Xgl+Jx85s7MkKNadmxRD72AUJR5KJPjgyUkPfDJeVpFlOmU9KJSuG+MnQx3wJ4c1GGcYhBEvMpgwl4jqC/Zg1LoUDMAKJ+FsIYOrVJeHAoGACwcwkU9Uus1vW0yjsNDtFZ2NdiXrNdRqPk/GyDXWivMVpfAw1EP9qWQv0zT5rTDL++1In5la60TW0WhH7QRlxW0KMVyqxZ5rfaROx4X5qrA4fYkZ1oMA7zJTgIiVH+X/i3MoXxmj3eeFVJ3ITXqSGr8qPspGe3QdnanczLN8pSECgYBYlAcWUwXj4AI1ABTh9R3vAaajcauCGdEVxu2tCygHC+/+c64UxBX6ysIqmt2Tkmdd1Jv8O32Ibv4Dhic7woNhHafFTnglLMfP9UMGTOcKv4Z7lF+CUZrrD2oE5ESS9zxtsyTC9CZWKnOZ5cYCH+BZ6bKhQLyMXle2au9QJLEebA==
    access-token-validity-time: 1800000
    refresh-token-validity-time: 86400000